spring:
  redis:
    port: 6600
    host: 39.107.245.58
    #password:
    database: 0
    jedis:
      pool:
        #最大连接数 负值表示没有限制
        max-active: 100
        #最大连接空闲
        max-idle: 8
        #最小连接空闲
        min-idle: 0
        #最大阻塞等待时间 负值没有限制
        max-wait: 60000
    timeout: 100000
port: 6600
